version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - database
    restart: unless-stopped
    container_name: api
    volumes:
      - ./src:/app/src

  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/database
    container_name: database

    # To Change
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongo
